### ISSUE TITLE
README.md Yi-6B-Chat-GGUF link doesn't seem to be the chat version

### ISSUE THREAD

**Issue by RoversX** [linyiLYi/voice-assistant#1]
This doesn't seem to be the chat version provided in README.md, I don't think TheBloke provided the 6B chat version of gguf format yet.

- [Yi-6B-Chat-GGUF，适用小显存平台](https://huggingface.co/TheBloke/Yi-6B-GGUF/blob/main/yi-6b.Q8_0.gguf)

This seems to be the chat version, I haven't tested it yet 
https://huggingface.co/XeIaso/yi-chat-6B-GGUF/blob/main/yi-chat-6b.Q8_0.gguf

**Comment by linyiLYi** [comment]
You are right. Thanks for pointing out. I'll update the README file shortly after.
