### ISSUE TITLE
加载模型的时候出现报错

### ISSUE THREAD

**Issue by CambridgeZ** [linyiLYi/voice-assistant#10]
在加载模型的时候出现下面的报错有没有大佬也遇到过😭
  Could not load Llama model from path: yi-chat-6b.Q2_K.gguf. Received error  (type=value_error)

**Comment by RoversX** [comment]
是不是路径问题，要在main.py里面改

**Comment by linyiLYi** [comment]
你要下载好这个模型文件，然后放在models文件夹下，把main.py对应的地方也要改一下
