### ISSUE TITLE
语音识别失败, On-device recognition is not supported for locale

### ISSUE THREAD

**Issue by RoversX** [linyiLYi/voice-assistant#3]
The problem seems to be caused by the "hear" module, which is discussed at https://github.com/sveinbjornt/hear/issues/20. (I tried other time zones and languages, same problem) Switch to whisper can be a solution? Any ideas?

<img width="1040" alt="Screenshot 2023-12-09 at 2 00 07 PM" src="https://github.com/linyiLYi/voice-assistant/assets/85817538/9a64c367-fcf4-4593-9b4d-d114ffdf94cb">
<img width="1464" alt="Screenshot 2023-12-09 at 2 00 45 PM" src="https://github.com/linyiLYi/voice-assistant/assets/85817538/5e541151-eda8-4cc3-ba37-e0ebcba4645f">

**Comment by linyiLYi** [comment]
You might need to add support for us-en in your Mac settings. You could refer to the following instruction page:
https://support.apple.com/en-hk/HT208316

**Comment by RoversX** [comment]
> You might need to add support for us-en in your Mac settings. You could refer to the following instruction page: https://support.apple.com/en-hk/HT208316

Oh, The problem was the Region. Thanks!
